source 'https://rubygems.org'

gem 'rails', '~> 4.0.1'
gem 'jbuilder', '~> 1.2'

gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'sass-rails', '~> 4.0.0'
gem 'slim-rails'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development do
  gem 'pry'
  gem 'sqlite3'
end

group :doc do
  gem 'sdoc', require: false
end
